### ISSUE TITLE
Console warning when requiring safe-identifier

### ISSUE THREAD

**Issue by coxmi** [eemeli/safe-identifier#1]
Hi there,
I'm getting this when requiring safe-identifier:
```
ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
```

Any ideas why this warning is showing?
Thanks!

**Comment by eemeli** [comment]
It's showing up because the package is using a Node.js feature that's still technically experimental.

That warning should be [going away soon](https://github.com/nodejs/modules/issues/485), as [conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports) are just about to move from "experimental" to "stable". In fact, updating to a more recent Node.js version may already get rid of the warning.

**Comment by coxmi** [comment]
Great, I'll check out the latest node in that case
Thank you for explaining!

**Comment by eemeli** [comment]
Closing as answered.
