### ISSUE TITLE
Question: why we drop separate reserved.mjs

### ISSUE THREAD

**Issue by xiaoxiangmoe** [eemeli/safe-identifier#2]
see https://github.com/eemeli/safe-identifier/commit/3f199dd02af195219fd622f0b4063653a5e14c4d

I found reserved.mjs was removed. But I don't know why it was removed.

**Comment by eemeli** [comment]
Because there was no benefit to it, and it was duplicating the same data. `index.js` and `index.mjs` are separate because there may be situations in which ESM tree-shaking will be able to drop out a part of the latter, but there's practically no situation in which using just a part of `reserved.js` makes sense.

Importing `safe-identifier/reserved` should now get you the same results from both ESM and CJS contexts.
